package com.softdelsur.agricola.service;

import com.softdelsur.agricola.entity.OrdenTrabajoUnidadTrabajoSubCuartel;
import com.softdelsur.agricola.repository.OrdenTrabajoUnidadTrabajoSubCuartelRepository;

public interface OrdenTrabajoUnidadTrabajoSubCuartelService {
	
	OrdenTrabajoUnidadTrabajoSubCuartel addOrdenTrabajoUnidadTrabajoSubCuartelRepository(OrdenTrabajoUnidadTrabajoSubCuartel ordenTrabajoUnidadTrabajoSubCuartel);

}
